# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [8]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array(list(range(5)))
print(array_1d, end='\n\n')

# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([list(range(5)) for _ in range(6)])
print(array_2d, end='\n\n')

# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([[list(range(5)) for _ in range(6)] for _ in range(7)])
print(array_3d, end='\n\n')

[0 1 2 3 4]

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

[[[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]



Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(array_1d.shape)
print(len(array_1d))
print(array_1d.dtype)
print(type(array_1d))

(5,)
5
int64
<class 'numpy.ndarray'>


In [10]:
# Attributes of 2-dimensional array
print(array_2d.shape)
print(len(array_2d))
print(array_2d.dtype)
print(type(array_2d))

(6, 5)
6
int64
<class 'numpy.ndarray'>


In [11]:
# Attributes of 3-dimensional array
print(array_3d.shape)
print(len(array_3d))
print(array_3d.dtype)
print(type(array_3d))

(7, 6, 5)
7
int64
<class 'numpy.ndarray'>


In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(array_2d, columns=['a', 'b', 'c', 'd', 'e'])
df

a  b  c  d  e
0  0  1  2  3  4
1  0  1  2  3  4
2  0  1  2  3  4
3  0  1  2  3  4
4  0  1  2  3  4
5  0  1  2  3  4

In [20]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7, 2, 3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# Create an array within a range of 0 and 100 with step 3
array_step = np.array(range(0, 100, 3))
array_step

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_randint = np.array(np.random.randint(low=0, high=10, size=(7, 2)))
array_randint

array([[3, 0],
       [0, 8],
       [3, 4],
       [5, 4],
       [4, 6],
       [0, 4],
       [5, 4]])

In [32]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random = np.array(np.random.rand(3, 5))
array_random

array([[0.81458591, 0.60898972, 0.91073961, 0.01988427, 0.92553055],
       [0.78959552, 0.03355321, 0.84236455, 0.85194294, 0.48410411],
       [0.99894328, 0.1953583 , 0.99320588, 0.95415214, 0.72441161]])

In [34]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_randint_42 = np.array(np.random.randint(low=0, high=10, size=(4, 6)))
array_randint_42

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_randint_for_unique = np.array(np.random.randint(1, 10, (3, 7)))

# Find the unique numbers in the array you just created
np.unique(array_randint_for_unique)

array([1, 2, 3, 4, 5, 7, 9])

In [39]:
# Find the 0'th index of the latest array you created
array_randint_for_unique[0, 0]

9

In [40]:
# Get the first 2 rows of latest array you created
array_randint_for_unique[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [41]:
# Get the first 2 values of the first 2 rows of the latest array
array_randint_for_unique[:2, :2]

array([[9, 1],
       [5, 3]])

In [43]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_ones_for_calculation = np.ones(shape=(3, 5)).astype(int)
array_randint_for_calculation = np.random.randint(low=0, high=10, size=(3, 5))
print(array_ones_for_calculation)
print(array_randint_for_calculation)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[9 1 9 3 7]
 [6 8 7 4 1]
 [4 7 9 8 8]]


In [44]:
# Add the two arrays together
arrays_sum = array_ones_for_calculation + array_randint_for_calculation
arrays_sum

array([[10,  2, 10,  4,  8],
       [ 7,  9,  8,  5,  2],
       [ 5,  8, 10,  9,  9]])

In [45]:
# Create another array of ones of shape (5, 3)
array_ones_vertical_for_calculation = np.ones(shape=(5, 3))
array_ones_vertical_for_calculation

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# Try add the array of ones and the other most recent array together
arrays_sum + array_ones_vertical_for_calculation

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [47]:
# Create another array of ones of shape (3, 5)
pass

In [49]:
# Subtract the new array of ones from the other most recent array
arrays_subtract = arrays_sum - array_ones_for_calculation
arrays_subtract

array([[9, 1, 9, 3, 7],
       [6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8]])

In [51]:
# Multiply the ones array with the latest array
arrays_subtract * array_ones_for_calculation

array([[9, 1, 9, 3, 7],
       [6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8]])

In [54]:
# Take the latest array to the power of 2 using '**'
arrays_subtract ** 2

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [56]:
# Do the same thing with np.square()
np.square(arrays_subtract)

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [60]:
# Find the mean of the latest array using np.mean()
np.mean(arrays_subtract)

6.066666666666666

In [61]:
# Find the maximum of the latest array using np.max()
np.max(arrays_subtract)

9

In [62]:
# Find the minimum of the latest array using np.min()
np.min(arrays_subtract)

1

In [63]:
# Find the standard deviation of the latest array
np.std(arrays_subtract)

2.6948510575210314

In [64]:
# Find the variance of the latest array
np.var(arrays_subtract)

7.262222222222222

In [65]:
# Reshape the latest array to (3, 5, 1)
arrays_subtract.reshape((3, 5, 1))

array([[[9],
        [1],
        [9],
        [3],
        [7]],

       [[6],
        [8],
        [7],
        [4],
        [1]],

       [[4],
        [7],
        [9],
        [8],
        [8]]])

In [66]:
# Transpose the latest array
arrays_subtract.T

array([[9, 6, 4],
       [1, 8, 7],
       [9, 7, 9],
       [3, 4, 8],
       [7, 1, 8]])

What does the transpose do?

In [67]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_randint_for_dot_1 = np.random.randint(low=0, high=10, size=(3, 3))
array_randint_for_dot_2 = np.random.randint(low=0, high=10, size=(3, 2))
print(array_randint_for_dot_1)
print(array_randint_for_dot_2)

[[0 8 6]
 [8 7 0]
 [7 7 2]]
[[0 7]
 [2 2]
 [0 4]]


In [68]:
# Perform a dot product on the two newest arrays you created
np.dot(array_randint_for_dot_1, array_randint_for_dot_2)

array([[16, 40],
       [14, 70],
       [14, 71]])

In [69]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_randint_for_dot_3 = np.random.randint(0, 10, (4, 3))
array_randint_for_dot_4 = np.random.randint(0, 10, (4, 3))
print(array_randint_for_dot_3)
print(array_randint_for_dot_4)

[[9 6 9]
 [8 6 8]
 [7 1 0]
 [6 6 7]]
[[4 2 7]
 [5 2 0]
 [2 4 2]
 [0 4 9]]


In [70]:
# Perform a dot product on the two newest arrays you created
np.dot(array_randint_for_dot_3, array_randint_for_dot_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [71]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_randint_for_dot_3, array_randint_for_dot_4.T)

array([[111,  57,  60, 105],
       [100,  52,  56,  96],
       [ 30,  37,  18,   4],
       [ 85,  42,  50,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [74]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_randint_for_comparison_1 = np.random.randint(0, 10, (3, 5))
array_randint_for_comparison_2 = np.random.randint(0, 10, (3, 5))
print(array_randint_for_comparison_1)
print(array_randint_for_comparison_2)

[[6 6 8 9 9]
 [2 6 0 3 3]
 [4 6 6 3 6]]
[[2 5 1 9 8]
 [4 5 3 9 6]
 [8 6 0 0 8]]


In [75]:
# Compare the two arrays with '>'
array_randint_for_comparison_1 > array_randint_for_comparison_2

array([[ True,  True,  True, False,  True],
       [False,  True, False, False, False],
       [False, False,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [76]:
# Compare the two arrays with '>='
array_randint_for_comparison_1 >= array_randint_for_comparison_2

array([[ True,  True,  True,  True,  True],
       [False,  True, False, False, False],
       [False,  True,  True,  True, False]])

In [77]:
# Find which elements of the first array are greater than 7
array_randint_for_comparison_1 > 7

array([[False, False,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [78]:
# Which parts of each array are equal? (try using '==')
array_randint_for_comparison_1 == array_randint_for_comparison_2

array([[False, False, False,  True, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [79]:
# Sort one of the arrays you just created in ascending order
np.sort(array_randint_for_comparison_1)

array([[6, 6, 8, 9, 9],
       [0, 2, 3, 3, 6],
       [3, 4, 6, 6, 6]])

In [80]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_randint_for_comparison_1)

array([[0, 1, 2, 3, 4],
       [2, 0, 3, 4, 1],
       [3, 0, 1, 2, 4]])

In [81]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_randint_for_comparison_1)

3

In [82]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_randint_for_comparison_1)

7

In [83]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_randint_for_comparison_1, axis=1)

array([3, 1, 1])

In [84]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_randint_for_comparison_1, axis=0)

array([1, 0, 1, 1, 1])

In [87]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-1.01907279,  0.12701224, -1.24944372,  1.94511561, -0.15333646],
       [-0.90698723, -0.81735416, -0.48312268, -0.56982835, -2.09159967],
       [ 1.26374053, -0.01548334, -0.02737645,  0.81787351, -1.05460447]])

# 다시보기: `np.linspace()`

In [89]:
# Create an array with 10 evenly spaced numbers between 1 and 100
# WTF
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.